import ThermalValvePassport.Core

/-!
# Reflected Thermal Valve

This module extracts the algebraic core needed by finite-temperature
Euclidean correlators.  The basic recurrence has two reciprocal geometric
roots, so it removes both the forward mode `q^n` and its reflected thermal
image `(q⁻¹)^n`.

The declarations are independent of QCD, quarkonium, complex analysis and
any particular physical model.
-/

namespace ThermalValvePassport

noncomputable section

variable {K : Type*} [Field K]

/-- Reciprocal-root coefficient `q + q⁻¹`. -/
def reflectedLambda (q : K) : K :=
  q + q⁻¹

/-- Second-order reciprocal-root bracket. -/
def reflectedBracket (lam : K) (x : ℕ → K) (n : ℕ) : K :=
  x (n + 2) - lam * x (n + 1) + x n

/-- Changing the bracket coefficient produces an exact local mismatch term. -/
theorem reflectedBracket_change_lambda
    (lam₀ lam₁ : K) (x : ℕ → K) (n : ℕ) :
    reflectedBracket lam₀ x n =
      reflectedBracket lam₁ x n + (lam₁ - lam₀) * x (n + 1) := by
  unfold reflectedBracket
  ring

/-- Every geometric mode is killed by its reciprocal-root bracket. -/
theorem reflectedBracket_geometric
    (c q : K) (hq : q ≠ 0) (n : ℕ) :
    reflectedBracket (reflectedLambda q) (fun k => c * q ^ k) n = 0 := by
  unfold reflectedBracket reflectedLambda
  simp only [pow_succ]
  field_simp [hq]
  ring

/-- The reciprocal geometric mode is killed by the same coefficient. -/
theorem reflectedBracket_inverseGeometric
    (c q : K) (hq : q ≠ 0) (n : ℕ) :
    reflectedBracket (reflectedLambda q) (fun k => c * (q⁻¹) ^ k) n = 0 := by
  have hinv : q⁻¹ ≠ 0 := inv_ne_zero hq
  have h := reflectedBracket_geometric c q⁻¹ hinv n
  simpa [reflectedLambda, inv_inv, add_comm] using h

/-- General two-root return generated by `q` and `q⁻¹`. -/
def reflectedReturn (q left right : K) (n : ℕ) : K :=
  left * q ^ n + right * (q⁻¹) ^ n

/-- The full two-root return is in the kernel of the reflected bracket. -/
theorem reflectedBracket_reflectedReturn
    (q left right : K) (hq : q ≠ 0) (n : ℕ) :
    reflectedBracket (reflectedLambda q) (reflectedReturn q left right) n = 0 := by
  unfold reflectedReturn reflectedBracket
  have hqroot := reflectedBracket_geometric left q hq n
  have hinvroot := reflectedBracket_inverseGeometric right q hq n
  unfold reflectedBracket at hqroot hinvroot
  linear_combination hqroot + hinvroot

/-- Finite-temperature reciprocal-image kernel, written without truncated
natural subtraction:

`(q^n + q^N (q⁻¹)^n) / (1 - q^N)`.

For `n ≤ N` this is the usual `(q^n + q^(N-n))/(1-q^N)`.
-/
def reflectedThermalKernel (q : K) (N n : ℕ) : K :=
  (q ^ n + q ^ N * (q⁻¹) ^ n) / (1 - q ^ N)

/-- The finite-temperature kernel is exactly annihilated by the reflected
bracket. -/
theorem reflectedBracket_reflectedThermalKernel
    (q : K) (N n : ℕ) (hq : q ≠ 0) :
    reflectedBracket (reflectedLambda q)
      (fun k => reflectedThermalKernel q N k) n = 0 := by
  let scale : K := (1 - q ^ N)⁻¹
  change reflectedBracket (reflectedLambda q)
      (fun k => scale * q ^ k + (scale * q ^ N) * (q⁻¹) ^ k) n = 0
  simpa [reflectedReturn] using
    reflectedBracket_reflectedReturn q scale (scale * q ^ N) hq n

/-- Exact mismatch of a thermal kernel `qᵢ` when read through a reference
coefficient `q`. -/
theorem reflectedBracket_kernel_mismatch
    (q qᵢ : K) (N n : ℕ) (hqᵢ : qᵢ ≠ 0) :
    reflectedBracket (reflectedLambda q)
        (fun k => reflectedThermalKernel qᵢ N k) n =
      (reflectedLambda qᵢ - reflectedLambda q) *
        reflectedThermalKernel qᵢ N (n + 1) := by
  rw [reflectedBracket_change_lambda
    (reflectedLambda q) (reflectedLambda qᵢ)]
  rw [reflectedBracket_reflectedThermalKernel qᵢ N n hqᵢ]
  simp

/-- Affine-plus-profile sequence used by the static-potential passport. -/
def affineProfile [CharZero K]
    (A B C : K) (s : ℕ → K) (n : ℕ) : K :=
  A + B * (n : K) + C * s n

/-- The ordinary second difference kills the affine return and preserves only
the supplied profile curvature. -/
theorem secondDifference_affineProfile [CharZero K]
    (A B C : K) (s : ℕ → K) (n : ℕ) :
    secondDifference (affineProfile A B C s) n =
      C * secondDifference s n := by
  unfold secondDifference affineProfile
  push_cast
  ring

/-- After subtracting the known profile channel, only an affine return remains. -/
theorem secondDifference_sub_profile_eq_zero [CharZero K]
    (A B C : K) (s : ℕ → K) (n : ℕ) :
    secondDifference
        (fun k => affineProfile A B C s k - C * s k) n = 0 := by
  unfold secondDifference affineProfile
  push_cast
  ring

end

end ThermalValvePassport
